apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  annotations: 
     argocd.argoproj.io/sync-wave: "-1"
  namespace: {{ .Values.namespace }}
data:
  APP_COLOR: {{ .Values.config.APP_COLOR }}

